### ISSUE TITLE
Grails 3 Support

### ISSUE THREAD

**Issue by bluesliverx** [bluesliverx/grails-spring-security-oauth2-provider#104]
I'm toying with the idea of diving into the brand new world of grails 3, and will need to update this plugin to use in my app. This requires major changes and perhaps should be done in a separate branch for now. At some point this should be master probably and we should have another branch for grails 2.x and before.

**Comment by domurtag** [comment]
+1 A Grails 3 version of spring-security-core was released about a month ago, so AFAIK there are no impediments (in terms of dependencies) to a Grails 3 version of this plugin

**Comment by SAgrawal14** [comment]
:+1:

**Comment by vinodpanicker** [comment]
+1

**Comment by donalmurtagh** [comment]
The lack of a Grails 3 version of this plugin (among others) is blocking me from upgrading to Grails 3, so :+1: from me too

**Comment by mariomatar** [comment]
+1

**Comment by e210** [comment]
+1

**Comment by bobby-vandiver** [comment]
I've spent the last few days looking into this and I've made really good progress. All of the plugin's core functionality has been upgraded and the functional tests are working now except the one testing `TokenEnhancer` support. 

Things I'm gonna wrap up this week before I push a branch out:

* Fix `TokenEnhancer` support.
* Revisit some of the integration tests that were mocking out dependencies and convert them to proper unit tests. 
* Port scripts over to Grails 3.x scripts.
* Do some general clean up to remove (now) dead bits of code.

**Comment by donalmurtagh** [comment]
@bobby-vandiver sounds like you're making great progress - much appreciated

**Comment by bobby-vandiver** [comment]
Just pushed the upgrade out to the [grails-3](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/tree/grails-3) branch. I still need to update the documentation and a few minor things. Nothing to stop someone from building the plugin and using it in their app.

**Comment by bluesliverx** [comment]
Awesome, thanks for doing that :)  Sorry I've been such a slacker on this project in the last while.

**Comment by bobby-vandiver** [comment]
I updated the documentation and rolled forward to Spring OAuth 2.0.8.RELEASE. The upgrade should be complete at this point.

@bluesliverx Can you look into setting up a Travis build for the Grails 3.x branch and publishing `3.0.0-SNAPSHOT` of the plugin for consumption?

Also, how do we want handle releases and branching going forward? Since Grails 3.x is the future, we probably want to branch the current `master` off as a `2.x` branch and merge the Grails 3.x changes into master. What are your thoughts?

**Comment by bluesliverx** [comment]
Sorry I forgot to do this today, hopefully I can get to it tomorrow, should be pretty easy to set up. I completely agree with you, master should be 3.x and we should have a 2.x branch.

**Comment by bluesliverx** [comment]
@bobby-vandiver, I see you added some tasks for doing acceptance testing in build.gradle.  Can you tell me what tasks you expect to run to run the full test suite?  We should probably add whatever it is to have the "check" task depend on them so they run automatically.

i.e. gradlew check runs acceptanceTest without basic auth, acceptanceTest with basic auth, and any other unit tests there are.

It seems also that the gradle tasks are still attempting to run grails, but maybe I'm just reading it wrong.

**Comment by bluesliverx** [comment]
Whoops, wrong button :)

**Comment by bluesliverx** [comment]
I've made some progress on this.  The docs have now been published, but unfortunately we only have one version at the moment, and it is for grails 3 now.  We may need to consider publishing the 2.x docs somewhere else possibly just for record keeping and those currently using it.

Things remaining to be done:
- Get doc publishing working just on released versions
- Add testing for specific grails versions (I'm not sure which we should run the acceptanceTest task for
- Verify that the bintrayUpload task doesn't also run acceptance tests automatically (looks like it does at the moment)
- Get bintray uploading working fully - I think we need the other gradle file for maven publishing, but it says the install task already exists for some reason. I need to find out which plugin is adding it and modify it possibly.

**Comment by bobby-vandiver** [comment]
@bluesliverx Sorry it's taken so long to get back to this. I pushed a few changes so that the functional tests get run with and without Basic Auth for the generated projects when executing the `acceptanceTest`.

The intention with the `acceptanceTest` task is the same as it was with version 2.x of the plugin: generate projects with different versions of Grails and run the functional test suite against the project. Instead of relying on the `testapps.config.groovy` file, the task just takes in the version of Grails as a property.

I would be in favor of leaving the `acceptanceTest` task as a standalone task so that `check` *only* applies to the plugin and then execute the `acceptanceTest` task against the versions of Grails we claim support for.

As far as versions of Grails to test against, I would say at least 3.0.11 and 3.0.12. I've tested locally against 3.0.9 and 3.0.11. When running the tests against a 3.0.10 application, you'll run into [grails-core issue #9459](https://github.com/grails/grails-core/issues/9459).

**Comment by bobby-vandiver** [comment]
@bluesliverx Have you had a chance to look into getting bintray uploading working any more? It'd be great if we could get an RC release out so more people are able to use the plugin and ensure we haven't introduced any subtle breakage with the upgrade to Grails 3.

**Comment by bluesliverx** [comment]
@bobby-vandiver sorry, been busy with work and life.  I've tried to add the acceptanceTest in, but it apparently has some issues on travis: https://travis-ci.org/bluesliverx/grails-spring-security-oauth2-provider/builds/109617654.  Could you take a look?  If I figure it out I'll let you know, but I don't really have time to dig in at the moment.

I've also started an RC1 build, hopefully bintray accepts that as valid.

**Comment by bobby-vandiver** [comment]
@bluesliverx The `acceptanceTest` uses the `grailsSDKsDir` property to determine where the Grails SDKs are to use for generating the test apps. If this isn't specified, it defaults to `sdks/grails` in the user's home directory such that:

```shell
$ ls -l ~/sdk/grails
2.3.10 -> grails-2.3.10
2.3.11 -> grails-2.3.11
2.3.5 -> grails-2.3.5
2.3.6 -> grails-2.3.6
2.3.7 -> grails-2.3.7
2.3.8 -> grails-2.3.8
2.3.9 -> grails-2.3.9
2.4.0 -> grails-2.4.0
2.4.1 -> grails-2.4.1
2.4.2 -> grails-2.4.2
2.4.3 -> grails-2.4.3
2.4.4 -> grails-2.4.4
2.4.5 -> grails-2.4.5
2.5.0 -> grails-2.5.0
2.5.3 -> grails-2.5.3
3.0.10 -> grails-3.0.10
3.0.11 -> grails-3.0.11
3.0.9 -> grails-3.0.9
```
Where each `grails-xxx` directory is the Grails SDK.

So basically, we just need a path to a directory containing the Grails SDKs on Travis so that we can specify that path with `-PgrailsSDKsDir=/path/to/grails/sdks`.

**Comment by bluesliverx** [comment]
For my reference later: http://blog.lanyonm.org/articles/2013/10/21/testing-multiple-grails-versions-travis-ci.html

**Comment by bluesliverx** [comment]
I've now run into this error:
```
:spring-security-oauth2-provider:bintrayUpload:spring-security-oauth2-provider:bintrayUpload: Could not find publication: maven.```

I can't find anything about it, but I'm guessing our bintray configuration is incorrect.

**Comment by bobby-vandiver** [comment]
@bluesliverx Is there anything I can do to help?

**Comment by bluesliverx** [comment]
I'm honestly not sure where to go from here.  I know Grails 3.1.x has a newer way of publishing plugins, I wonder if we upgrade to that version if it would actually work (see https://medium.com/@benorama/how-to-publish-your-grails-3-plugin-to-bintray-c341b24f567d#.87ucir85i).  I'm sorry I don't have a lot of time to dedicate to this, and the error is not very helpful at the moment.  Nothing obvious showed up on google.

**Comment by bluesliverx** [comment]
At last, success! https://bintray.com/bluesliverx/grails-plugins/spring-security-oauth2-provider/3.0.0-RC1/view

3.0.0-RC1 should be available from bintray now.

**Comment by bluesliverx** [comment]
I think this issue can be closed after someone verifies they can grab the dependency with no problems.

**Comment by bobby-vandiver** [comment]
@bluesliverx It looks like the the pom and jar aren't being published. 

I took a look at what the Spring Security Core plugin is using (since it is still built with 3.0.x) and they're pulling in a few gradle scripts that handle the publishing and upload:

```groovy
apply from: 'https://raw.githubusercontent.com/grails/grails-profile-repository/master/profiles/plugin/templates/grailsCentralPublishing.gradle'
apply from: 'https://raw.githubusercontent.com/grails/grails-profile-repository/master/profiles/plugin/templates/bintrayPublishing.gradle'
```

https://github.com/grails-plugins/grails-spring-security-core/blob/master/gradle/plugin.gradle

Maybe it's worthwhile to do the same for this plugin?

I'll take a look at the acceptance tests this week when I have a bit more free time to investigate. :)

**Comment by bobby-vandiver** [comment]
Spent a while looking and tinkering with this. Turns out the secret sauce is to include the correct repository in `build.gradle`:

```groovy
repositories {
// ...
    maven { url "http://dl.bintray.com/bluesliverx/grails-plugins" }
}

dependencies {
// ...
    compile "org.grails.plugins:spring-security-oauth2-provider:3.0.0-RC1"
}
```

What's left to do to get this included as part of the official Grails plugin repo?

**Comment by bluesliverx** [comment]
I sent a request to the grails team through the "Include My Package" button here: https://bintray.com/grails/plugins

We just have to wait for their approval and it will be in.  Thanks for tracking this down!  Interesting about the repositories, I wonder if that is why it complained about no maven publisher...  That's a really terrible error message if that's the case.

**Comment by bluesliverx** [comment]
It is now included in the grails plugin repo: https://bintray.com/grails/plugins.

Are the tests running successfully again?  If so I think we can close this issue finally.

**Comment by davydotcom** [comment]
unfortunately cant get it to work on latest grails 3.1.6

**Comment by bluesliverx** [comment]
@davydotcom Can you provide some more details here on what you are seeing?  You may want to just file another issue since this one is rather large and old now.

**Comment by davydotcom** [comment]
All is well . Sorry it seems after upgrading to Grails 3 the encoding on old access tokens in the database got corrupt

**Comment by bluesliverx** [comment]
No problem, good to know in case someone else runs into it.

**Comment by bobby-vandiver** [comment]
@bluesliverx I've got the `acceptanceTest` task working as part of the build now. Right now the build is testing against Grails 3.0.17 and Grails 3.1.7. I think with this, we can now safely close this issue. Huzzah!

**Comment by bobby-vandiver** [comment]
I spoke too soon. I'm going to refactor the `callGrails` method to not use `ant.exec` to execute `grails` and echo the output so the build doesn't get terminated due to lack of output.

**Comment by bluesliverx** [comment]
@bobby-vandiver I opened #118 to track this to make sure we get it resolved. I figured this issue should just be closed. :)
