### ISSUE TITLE
The build #3.0.0-RC2 is falling

### ISSUE THREAD

**Issue by sting2804** [bluesliverx/grails-spring-security-oauth2-provider#125]
Because of this spring-security-oauth2-provider:3.0.0-RC2 is not available in the repo

**Comment by bluesliverx** [comment]
The master build is failing, yes, due to some problem in travis itself that we haven't been able to figure out yet.  Something is timing out in the acceptance testing.

However, the 3.0,0-RC2 build did work just fine: https://travis-ci.org/bluesliverx/grails-spring-security-oauth2-provider/builds/148930383.  And the artifacts are here: https://bintray.com/bluesliverx/grails-plugins/org.grails.plugins%3Aspring-security-oauth2-provider/3.0.0-RC2#files/org/grails/plugins/spring-security-oauth2-provider/3.0.0-RC2

Let me know if you see any other issues with this.
