### ISSUE TITLE
OAuth2 filters for Password Credentials and Refresh Token grant types

### ISSUE THREAD

**Issue by amruthasuri** [bluesliverx/grails-spring-security-oauth2-provider#142]
Hi,

    I don't see any filters for the Password credentials and Refresh token grant types. Please let us know how to handle these grant types using /oauth/token endpoint as specified in the example flows

http://bluesliverx.github.io/grails-spring-security-oauth2-provider/v3/manual/guide/exampleFlows.html

   and also please direct me towards configuring the custom authentication provider.

Thanks and Regards
Suri Babu B

**Comment by bluesliverx** [comment]
I'm not sure why you are looking for the filters.  It's been a very long time since I've looked at this, but as long as you configure things correctly in the grails config, it should register filters for you, that's basically the point of this plugin. If you want to register filters yourself, perhaps you should look at the spring oauth documentation to do it.
