### ISSUE TITLE
Unique constraint causes a token retrieval to fail

### ISSUE THREAD

**Issue by bluesliverx** [bluesliverx/grails-spring-security-oauth2-provider#50]
In the default implementation, if you re-request a set of tokens using any grant type, it just replaces the tokens that existed previously.  However, with the GORM classes now the unique constraint causes a failure to save.  This should be replaced with a replacement of the existing token instead of using the unique constraint.

Thoughts on how to do this?

**Comment by akistanov** [comment]
+1
The problem happens when you try to reacquire existed token.
This can be fixed by adding flush: true to gorm token delete() method call.
For example:
```
    void removeAccessToken(String tokenValue) {
        ...
        gormAccessToken?.delete(flush: true)
    }
```

Also it seems that you need convert gormToken.scope value to POJO Set when you assign this value to token:
```
    private OAuth2AccessToken createOAuth2AccessToken(gormAccessToken) {
        ...
        token.scope = new HashSet<>(gormAccessToken."$scopePropertyName")
        return token
    }
```
In opposite the Hibernate PersitentSet will be assigned to token.scope and you will recieve Hibernate exception: Found two representations of same collection when trying trying to save new gormToken with this value.

**Comment by bobby-vandiver** [comment]
@akistanov Could you provide a sample app or detailed instructions to reproduce this? I've tried to reproduce this issue but thus far have been unable to. I'd really like to get this and the related issue #49 resolved soon.

**Comment by bluesliverx** [comment]
Finally was able to reproduce this with a small app.  Basically it took:

1) Multi tenant plugin
2) OAuth2 provider plugin
3) AccessToken being multi tenanted (added a tenantId property)
4) Made the unique constraint apply to the tenantId instead of just having it be "true"

Only when I had all of those conditions did it throw the error.  Note that this a very typical use case.  My initial reaction on finding this was to back out the multi tenant plugin and try a unique:'otherProperty' constraint on a vanilla spring security oauth2 provider app, but that actually worked.

See this git repository for a full non-working example: https://github.com/bluesliverx/oauth2-bug-report-50
Also note the "no-multi-tenant" branch, which is testing if it breaks just using a unique:'otherProperty' value.  This actually works however.

Start up the test app and hit http://localhost:8080/oauth2-test/oauth/token?grant_type=password&client_id=clientId&client_secret=clientSecret&username=admin&password=password&scope=all in your browser.  Make sure it gets a valid token (no need to verify it really, just make sure you get JSON back), and then refresh.  It should explode the second time.

**Comment by bobby-vandiver** [comment]
I pushed a fix on a branch for review. Instead of attempting to delete an existing token and then recreate it, now we'll update the token or create the token if one doesn't already exist. The net result is the same as before.

@bluesliverx, I'd like you to take a look and see if there are any other issues before merging this to master. I've confirmed it resolves the constraint violation exception and all of the automated tests pass. I'd like to do a little more testing and see if we can test this in an automated way to guard against regressions in the future.

**Comment by bluesliverx** [comment]
Sorry @bobby-vandiver, I keep meaning to take a look at this, but I foolishly didn't push my test app into a repo somewhere and it's on my home computer that I don't get on a lot.  I'll try to take care of this soon, but I think it's probably good and we can go ahead and merge and release a new version.

**Comment by bobby-vandiver** [comment]
I merged the change to master. Closing this issue for now.
