### ISSUE TITLE
invalid_scope error occurs when exchanging auth code for access token

### ISSUE THREAD

**Issue by domurtag** [bluesliverx/grails-spring-security-oauth2-provider#64]
Hi,

I'm trying to implement an OAuth provider app using your plugin. I've also implemented a client Grails app (to test the provider). When I test the authorization code grant flow, I'm able to retrieve an authorization code, but when I try to exchange this for an access token, I get this error

````json
{
    "error": "invalid_scope", 
    "error_description": "Empty scope (either the client or the user is not allowed the requested scopes)"
}
````
I've described the problem in further detail in [this stackoverflow post](http://stackoverflow.com/questions/28883540/implementing-an-oauth2-provider-with-grails).

You can reproduce the error by downloading the [provider](https://github.com/domurtag/oauth2-provider) and [client](https://github.com/domurtag/oauth-client) apps and following these instructions:

 - Start the provider app with `grails run-app`
 - Start the client app on port 9090 with `grails run-app -Dserver.port=9090`
 - On the homepage of the client app click the "OAuth Login" link. This redirects to the provider app and prompts you to login. Enter the username "me", password "password", and click the "Authorize" button in the confirmation dialog that follows.

Thanks in advance!

**Comment by bobby-vandiver** [comment]
I just pushed a fix for this.

 The temporary workaround until this is included in a new release of the plugin is to include the `scope` parameter in the request to the token endpoint with the same value as the `scope` parameter used in the request to the authorization endpoint.

It seems this crept in during the upgrade to Spring OAuth 2.x. Ironically, we have a [functional test](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/blob/master/test/functional/test/oauth2/AuthorizationCodeFunctionalSpec.groovy#L165) that exercises this exact scenario. However, I made the mistake of blindly adding the `scope` parameter every where in the test data in order to get the newer version of Spring OAuth integrated. 

Thanks for letting us know about this! :smile:

**Comment by bluesliverx** [comment]
Thanks Bobby for taking care of this.  Do you want me to post an answer on stackoverflow?

**Comment by bobby-vandiver** [comment]
Already taken care of. :wink:

**Comment by domurtag** [comment]
Thanks a lot for resolving this so quickly. I'll try out your workaround tomorrow. Would it be possible for you to release a (snapshot) version that includes the fix if you haven't already done so?

I'll accept your stackoverflow answer now.

**Comment by bluesliverx** [comment]
I'll see what I can do about a build.  It's difficult since I used to build it on a build server at my old job.  I really need to migrate the project to travisci or something.

**Comment by domurtag** [comment]
Given that it's just a SNAPSHOT release, I don't think it would be unreasonable to do the release simply by running `grails publish-plugin` on your local machine.

**Comment by bluesliverx** [comment]
Exactly what I'm planning on doing.  The difficult part is tracking down my credentials again ;)

**Comment by domurtag** [comment]
I had that problem too. My solution is to use the same password everywhere, what could possibly go wrong ;)

You might be able to reset your password via the plugins section of the Grails website.

**Comment by domurtag** [comment]
If you do manage to release the new version, if you could leave a comment here to let me know it would be much appreciated. Otherwise, I'll just clone the repo and include it as a local plugin.

**Comment by bluesliverx** [comment]
I've released the new version.
On a side note, it took me a few hours to finally figure out the issues with deploying using the release plugin, turns out I had mismatched plugin dependencies.  It is fixed now, and I have a travisci build working as well so it will be automatically updated on every commit (if the build passes).

**Comment by domurtag** [comment]
great work, thanks a lot
