### ISSUE TITLE
Reusing an unexpired auth token on refresh

### ISSUE THREAD

**Issue by kkaminski** [bluesliverx/grails-spring-security-oauth2-provider#81]
We're trying to work out an issue where the same user is using multiple devices and we don't want to prompt for their user/password if it's not necessary.  Take the following for example:

AT = Access Token
RT = Refresh Token
(Assume initial ATs can be obtained using the password grant type and both devices get the same AT)

Device 1:
1. Refresh, new AT
5. Bad AT
6. Refresh denied (bad RT)
7. Need Password for AT, new RT ... Repeats every time it expires

Device 2:
2. Bad AT 
3. Refresh denied (bad RT)
4. Need Password for new AT/RT

Then, if I try setting "grails.plugin.springsecurity.oauthProvider.tokenServices.reuseRefreshToken = true", I believe the following would happen:

Device 1:
1. Refresh, new AT
4. Bad AT
5. Refresh, new AT… Repeats every request

Device 2:
2. Bad AT
3. Refresh, new AT

It seems like this could be resolved by having the refresh return an AT if it isn't expired, but I didn't see any flags to set that in the plugin or any way to do that.

I assume we're not the first to encounter this type of problem, so I thought I'd reach out for thoughts/suggestions.

**Comment by bluesliverx** [comment]
Hopefully I'm understanding your problem correctly, but it seems that you would like something similar to "reuseRefreshToken" but for access tokens.

I'm curious why you want to have the same access token for both devices?  Typically you would consider these different clients and so they would each have their own access token.  If you were to share an access token this could be a potential security vulnerability if the access token is compromised.  Access tokens are typically known (or can be known) to the user and are therefore easier to steal/compromise, while refresh tokens are meant to be used on the backend and are meant to be more heavily protected.  Hence why I could see reusing the refresh token, but not reusing the access tokens.

**Comment by kkaminski** [comment]
Thanks for your response.  Maybe our model is not typical?  Let me explain a little further.

We have our "clients" set up as applications which can be installed on mobile device(s). Users register with our system and are given an access token per application.  We don't need to be aware of what device or devices they're using, it's all tied to a particular user/application pair.  That way we can control the clients that get added.  I'm not sure how/if it would work as user/device.  It seems like our client tables would get bogged down and we'd have less control.

What I was suggesting was a reuse of the access token only if it's not expired when requesting a refresh token, but I'm not sure if that violates the RFC.

**Comment by dynamind** [comment]
Your explanation is a little hard to follow, but it sounds like you're doing some kind of pre-authorization, like a token baked into what you call the user/application pair. Shouldn't you just hand out RTs instead? It shouldn't really matter which device gets which AT. Any device can use the (longer lived) RT to request new (short lived) ATs as needed. In practice they will get the same AT if one exists.

Setting `reuseRefreshToken` to true controls how `DefaultTokenServices` deals with existing RTs. Code is easy to understand:

    if (!reuseRefreshToken) {
        tokenStore.removeRefreshToken(refreshToken); // This kills your valid RT
        refreshToken = createRefreshToken(authentication);
    }

So setting `reuseRefreshToken` to true ensures the existing RT remains valid. This is what you want because the other devices still have the old RT which would have been invalidated.

The user should only need to authenticate when the RT is expired, which isn't very often in normal circumstances. The default configuration of the OAuth Provider plugin is 30 days, but you could increase that to 6 months or whatever. Please note that long-lived tokens are considered a security threat.

**Comment by kkaminski** [comment]
@dynamind Thanks for your response.  I'm sorry for the confusion.  The problem I'm trying to address is when a user is running an application on 2 different devices at the same time.  The client ID is the ID of the application, not the device.  We are not pre-authorizing per-se, but we do add clients in advance, then create access tokens as the clients request them on behalf of the users.  Then, we request the access/refresh token pair in the traditional manner for the "Resource Owner Password Credentials Grant".

If you can follow the logic in my first example above, you can see that as soon as the first device refreshes, it will invalidate the access token being used by the second device and since the refresh token is invalid also, they'll have to request the password.  Then, in my second example, I showed how reuseRefreshToken will also create a new access token and invalidate the second device, then they'll need to refresh for every request.

I don't think this is necessarily an oddball case, which is why I was trying to suggest a workaround (returning the existing access token if it's not expired).  Any suggestions are appreciated!

**Comment by dynamind** [comment]
@kkaminski did you manage to achieve what you want with this?

**Comment by kkaminski** [comment]
Hi Roy,

Thanks for checking up on this.  What you described is basically what we
were thinking we'd have to do when I originally wrote to you, so you did
validate that for us and we appreciate it!

We actually haven't handled this situation yet since we're slowly rolling
out our OAuth implementation and multiple device users isn't a problem for
us quite yet.  We want to avoid a custom implementation that would be
difficult to maintain and has the potential to decrease security for us.
It just didn't seem like this scenario was out of the ordinary.

if you or the team there has any other thoughts, we'd love to hear them and
really appreciate the assistance!

On Fri, Apr 24, 2015 at 10:48 AM, Roy Willemse <notifications@github.com>
wrote:

> @kkaminski <https://github.com/kkaminski> did you manage to achieve what
> you want with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bluesliverx/grails-spring-security-oauth2-provider/issues/81#issuecomment-95952915>
> .
>



-- 
*Kathy Kaminski*
kkaminski@skillz.com <jspiewak@skillz.com>
*skill**z*

Follow us on our blog: http://www.skillz.com/blog

CONFIDENTIALITY NOTICE: The materials in this electronic mail transmission
(including attachments) are private and confidential and are the property
of the sender, Skillz Inc. The information contained in the material is
intended only for the use of the named addressee(s). If you are not a named
addressee, be advised that any unauthorized disclosure, copying,
distribution or the taking of any action in reliance on the contents of
this material is strictly prohibited. If you have received this electronic
mail transmission in error, please immediately notify the sender by sending
an e-mail message and thereafter, destroy it immediately.

**Comment by bobby-vandiver** [comment]
@kkaminski I'm not sure how feasible it is for your situation, but you could implement [dynamic client registration](https://tools.ietf.org/html/draft-ietf-oauth-dyn-reg-28). Your application could ship with some information that it can exchange for valid client credentials to uniquely identify itself. Then each client (application) could be assigned its own unique access token and refresh token.

You might also look at what Google does for [installed applications](https://developers.google.com/identity/protocols/OAuth2InstalledApp), since this sounds similar to your use case.

**Comment by bobby-vandiver** [comment]
@kkaminski Have you had any luck achieving your desired outcome?

**Comment by bobby-vandiver** [comment]
Closing this due to lack of feedback.
