### ISSUE TITLE
Saving an authorization code shouldn't fail silently

### ISSUE THREAD

**Issue by donalmurtagh** [bluesliverx/grails-spring-security-oauth2-provider#90]
In [GormAuthorizationCodeService](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/blob/master/grails-app/services/grails/plugin/springsecurity/oauthprovider/GormAuthorizationCodeService.groovy) an instance of `AuthorizationCode` is saved like so

    protected void store(String code, OAuth2Authentication authentication) {
        def (className, codePropertyName, authenticationPropertyName) = getAuthorizationCodeConfiguration()
        def ctorArgs = [
                (codePropertyName): code,
                (authenticationPropertyName): oauth2AuthenticationSerializer.serialize(authentication)
        ]

        Class AuthorizationCode = getAuthorizationCodeClass(className)
        AuthorizationCode.newInstance(ctorArgs).save()
    }

A problem with this is that if saving the object fails there is no exception thrown or other obvious notification. In my case this happened because the `authentication` field exceeded the max allowed size.

Can I suggest that the last line above be changed to:

        AuthorizationCode.newInstance(ctorArgs).save(failOnError: true)

**Comment by bluesliverx** [comment]
It would be better to call validate on the object and throw an exception there instead of using failOnError.

**Comment by bobby-vandiver** [comment]
I think we've got three options:

1. Validate then save:
	```groovy
	def authorizationCode = AuthorizationCode.newInstance(ctorArgs)

	if (!authorizationCode.validate()) {
		throw new ValidationException("report validation errors")
	}

	authorizationCode.save()
	```
2. Since `save` implicitly calls `validate` and returns null if validation fails, just save and check the result:
	```groovy
	def authorizationCode = AuthorizationCode.newInstance(ctorArgs)

	if (!authorizationCode.save()) {
		throw new ValidationException("report validation errors")
	}
	```
3. Save and fail on error and let a Grails `ValidationException` be thrown if necessary:

	```groovy
	AuthorizationCode.newInstance(ctorArgs).save(failOnError: true)
	```

@bluesliverx  Ordinarily I would agree that `failOnError` is a bad idea, but I'm not seeing the benefit in _not_ using it in this case. Based on this issue and a previous one a few months back, the only time the save is problematic is when a validation error occurs due to not enough space being allocated for the `authentication` field. This isn't a "typical" validation error that can be recovered from like an invalid username. Is there something I'm missing?

**Comment by bluesliverx** [comment]
I'm only recommending not using `failOnError` due to performance concerns.  I've seen it at least once from grails core devs to not use it and instead the other ideas you mentioned above (by the way, good call about (2); I completely forgot about checking the return value there and would prefer it to (1) above).

The problem if we throw an exception is there is no really good place for a dev to catch that error and display better errors/warnings to the user if they desire unless they override the AuthorizationCodeService.  Having mostly been out of the grails world for awhile and been in straight java development, I would recommend wrapping the object not passing validation in a custom exception and throwing that.  That would enable the dev to create a URL mapping for the exception (since it's unique from other validation exceptions) and to display custom errors, etc depending on what the state of the domain class is.  They could also access the errors (authorizationCode.errors.allErrors) and combine that with the `message` function to use the i18n messages to render errors.  In fact, I would recommend we implement something like that by default, but I don't think it's absolutely necessary since where people care about it, they will override it with their own handling.

Having said that, I'm fine with whatever you think is best in this situation.  I'm just recommending what I would appreciate seeing from an integration standpoint to make my life easier.

Having this functionality would also make it easier for devs who decide to override the authorization code with their own functionality, but in that case they'd most likely have to override `AuthorizationCodeService` as well, so maybe it's a moot point.

**Comment by donalmurtagh** [comment]
Personally, I don't see much difference between the 3 options proposed by @bobby-vandiver, in each case an exception will be thrown if the `AuthorizationCode` is invalid.

In the case where the validation failure occurs due to the size of the `authentication` field being too small, I don't think catching this exception and displaying warnings to the user is relevant, because this error is irrecoverable and can only be fixed by making a change to the database/domain model.

The problem at the moment is that when this occurs, the system fails silently and it takes quite a bit of effort to track down the cause of the problem. Obviously this would be much simpler if an exception is thrown at the point of failure.

**Comment by bobby-vandiver** [comment]
I had not really considered the scenario @bluesliverx put forth, so I made a bit of a compromise and created a `ValidationException` subclass that is thrown if a `save` fails. This should satisfy everyone's needs.

**Comment by donalmurtagh** [comment]
Is this change available in the latest SNAPSHOT release?

**Comment by bobby-vandiver** [comment]
The automated build publishes a new SNAPSHOT for every successful build.

**Comment by donalmurtagh** [comment]
I didn't realise that, thanks for the info
